# Generated by Django 5.1.5 on 2025-02-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photo/'),
        ),
    ]
