# Generated by Django 5.1.5 on 2025-02-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_premium_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium_user',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
